/**
 * Complete list of countries (ISO 3166-1 alpha-2).
 * Sorted alphabetically by Italian label, with Italy first for convenience.
 */
export const COUNTRIES = [
	{ code: "IT", label: "Italia" },
	{ code: "AF", label: "Afghanistan" },
	{ code: "AL", label: "Albania" },
	{ code: "DZ", label: "Algeria" },
	{ code: "AD", label: "Andorra" },
	{ code: "AO", label: "Angola" },
	{ code: "AG", label: "Antigua e Barbuda" },
	{ code: "SA", label: "Arabia Saudita" },
	{ code: "AR", label: "Argentina" },
	{ code: "AM", label: "Armenia" },
	{ code: "AU", label: "Australia" },
	{ code: "AT", label: "Austria" },
	{ code: "AZ", label: "Azerbaigian" },
	{ code: "BS", label: "Bahamas" },
	{ code: "BH", label: "Bahrein" },
	{ code: "BD", label: "Bangladesh" },
	{ code: "BB", label: "Barbados" },
	{ code: "BE", label: "Belgio" },
	{ code: "BZ", label: "Belize" },
	{ code: "BJ", label: "Benin" },
	{ code: "BT", label: "Bhutan" },
	{ code: "BY", label: "Bielorussia" },
	{ code: "BO", label: "Bolivia" },
	{ code: "BA", label: "Bosnia ed Erzegovina" },
	{ code: "BW", label: "Botswana" },
	{ code: "BR", label: "Brasile" },
	{ code: "BN", label: "Brunei" },
	{ code: "BG", label: "Bulgaria" },
	{ code: "BF", label: "Burkina Faso" },
	{ code: "BI", label: "Burundi" },
	{ code: "KH", label: "Cambogia" },
	{ code: "CM", label: "Camerun" },
	{ code: "CA", label: "Canada" },
	{ code: "CV", label: "Capo Verde" },
	{ code: "TD", label: "Ciad" },
	{ code: "CL", label: "Cile" },
	{ code: "CN", label: "Cina" },
	{ code: "CY", label: "Cipro" },
	{ code: "CO", label: "Colombia" },
	{ code: "KM", label: "Comore" },
	{ code: "KP", label: "Corea del Nord" },
	{ code: "KR", label: "Corea del Sud" },
	{ code: "CI", label: "Costa d'Avorio" },
	{ code: "CR", label: "Costa Rica" },
	{ code: "HR", label: "Croazia" },
	{ code: "CU", label: "Cuba" },
	{ code: "DK", label: "Danimarca" },
	{ code: "DM", label: "Dominica" },
	{ code: "EC", label: "Ecuador" },
	{ code: "EG", label: "Egitto" },
	{ code: "SV", label: "El Salvador" },
	{ code: "AE", label: "Emirati Arabi Uniti" },
	{ code: "ER", label: "Eritrea" },
	{ code: "EE", label: "Estonia" },
	{ code: "SZ", label: "Eswatini" },
	{ code: "ET", label: "Etiopia" },
	{ code: "FJ", label: "Figi" },
	{ code: "PH", label: "Filippine" },
	{ code: "FI", label: "Finlandia" },
	{ code: "FR", label: "Francia" },
	{ code: "GA", label: "Gabon" },
	{ code: "GM", label: "Gambia" },
	{ code: "GE", label: "Georgia" },
	{ code: "DE", label: "Germania" },
	{ code: "GH", label: "Ghana" },
	{ code: "JM", label: "Giamaica" },
	{ code: "JP", label: "Giappone" },
	{ code: "DJ", label: "Gibuti" },
	{ code: "JO", label: "Giordania" },
	{ code: "GR", label: "Grecia" },
	{ code: "GD", label: "Grenada" },
	{ code: "GT", label: "Guatemala" },
	{ code: "GN", label: "Guinea" },
	{ code: "GW", label: "Guinea-Bissau" },
	{ code: "GQ", label: "Guinea Equatoriale" },
	{ code: "GY", label: "Guyana" },
	{ code: "HT", label: "Haiti" },
	{ code: "HN", label: "Honduras" },
	{ code: "IN", label: "India" },
	{ code: "ID", label: "Indonesia" },
	{ code: "IR", label: "Iran" },
	{ code: "IQ", label: "Iraq" },
	{ code: "IE", label: "Irlanda" },
	{ code: "IS", label: "Islanda" },
	{ code: "MH", label: "Isole Marshall" },
	{ code: "SB", label: "Isole Salomone" },
	{ code: "IL", label: "Israele" },
	{ code: "KZ", label: "Kazakistan" },
	{ code: "KE", label: "Kenya" },
	{ code: "KG", label: "Kirghizistan" },
	{ code: "KI", label: "Kiribati" },
	{ code: "KW", label: "Kuwait" },
	{ code: "LA", label: "Laos" },
	{ code: "LS", label: "Lesotho" },
	{ code: "LV", label: "Lettonia" },
	{ code: "LB", label: "Libano" },
	{ code: "LR", label: "Liberia" },
	{ code: "LY", label: "Libia" },
	{ code: "LI", label: "Liechtenstein" },
	{ code: "LT", label: "Lituania" },
	{ code: "LU", label: "Lussemburgo" },
	{ code: "MK", label: "Macedonia del Nord" },
	{ code: "MG", label: "Madagascar" },
	{ code: "MW", label: "Malawi" },
	{ code: "MY", label: "Malaysia" },
	{ code: "MV", label: "Maldive" },
	{ code: "ML", label: "Mali" },
	{ code: "MT", label: "Malta" },
	{ code: "MA", label: "Marocco" },
	{ code: "MR", label: "Mauritania" },
	{ code: "MU", label: "Mauritius" },
	{ code: "MX", label: "Messico" },
	{ code: "FM", label: "Micronesia" },
	{ code: "MD", label: "Moldavia" },
	{ code: "MC", label: "Monaco" },
	{ code: "MN", label: "Mongolia" },
	{ code: "ME", label: "Montenegro" },
	{ code: "MZ", label: "Mozambico" },
	{ code: "MM", label: "Myanmar" },
	{ code: "NA", label: "Namibia" },
	{ code: "NR", label: "Nauru" },
	{ code: "NP", label: "Nepal" },
	{ code: "NI", label: "Nicaragua" },
	{ code: "NE", label: "Niger" },
	{ code: "NG", label: "Nigeria" },
	{ code: "NO", label: "Norvegia" },
	{ code: "NZ", label: "Nuova Zelanda" },
	{ code: "OM", label: "Oman" },
	{ code: "NL", label: "Paesi Bassi" },
	{ code: "PK", label: "Pakistan" },
	{ code: "PW", label: "Palau" },
	{ code: "PA", label: "Panama" },
	{ code: "PG", label: "Papua Nuova Guinea" },
	{ code: "PY", label: "Paraguay" },
	{ code: "PE", label: "Perù" },
	{ code: "PL", label: "Polonia" },
	{ code: "PT", label: "Portogallo" },
	{ code: "QA", label: "Qatar" },
	{ code: "GB", label: "Regno Unito" },
	{ code: "CZ", label: "Repubblica Ceca" },
	{ code: "CF", label: "Repubblica Centrafricana" },
	{ code: "CG", label: "Repubblica del Congo" },
	{ code: "CD", label: "Repubblica Democratica del Congo" },
	{ code: "DO", label: "Repubblica Dominicana" },
	{ code: "RO", label: "Romania" },
	{ code: "RW", label: "Ruanda" },
	{ code: "RU", label: "Russia" },
	{ code: "KN", label: "Saint Kitts e Nevis" },
	{ code: "VC", label: "Saint Vincent e Grenadine" },
	{ code: "LC", label: "Santa Lucia" },
	{ code: "WS", label: "Samoa" },
	{ code: "SM", label: "San Marino" },
	{ code: "ST", label: "São Tomé e Príncipe" },
	{ code: "SN", label: "Senegal" },
	{ code: "RS", label: "Serbia" },
	{ code: "SC", label: "Seychelles" },
	{ code: "SL", label: "Sierra Leone" },
	{ code: "SG", label: "Singapore" },
	{ code: "SY", label: "Siria" },
	{ code: "SK", label: "Slovacchia" },
	{ code: "SI", label: "Slovenia" },
	{ code: "SO", label: "Somalia" },
	{ code: "ES", label: "Spagna" },
	{ code: "LK", label: "Sri Lanka" },
	{ code: "US", label: "Stati Uniti" },
	{ code: "ZA", label: "Sudafrica" },
	{ code: "SD", label: "Sudan" },
	{ code: "SS", label: "Sudan del Sud" },
	{ code: "SR", label: "Suriname" },
	{ code: "SE", label: "Svezia" },
	{ code: "CH", label: "Svizzera" },
	{ code: "TJ", label: "Tagikistan" },
	{ code: "TZ", label: "Tanzania" },
	{ code: "TH", label: "Thailandia" },
	{ code: "TL", label: "Timor Est" },
	{ code: "TG", label: "Togo" },
	{ code: "TO", label: "Tonga" },
	{ code: "TT", label: "Trinidad e Tobago" },
	{ code: "TN", label: "Tunisia" },
	{ code: "TR", label: "Turchia" },
	{ code: "TM", label: "Turkmenistan" },
	{ code: "TV", label: "Tuvalu" },
	{ code: "UA", label: "Ucraina" },
	{ code: "UG", label: "Uganda" },
	{ code: "HU", label: "Ungheria" },
	{ code: "UY", label: "Uruguay" },
	{ code: "UZ", label: "Uzbekistan" },
	{ code: "VU", label: "Vanuatu" },
	{ code: "VA", label: "Vaticano" },
	{ code: "VE", label: "Venezuela" },
	{ code: "VN", label: "Vietnam" },
	{ code: "YE", label: "Yemen" },
	{ code: "ZM", label: "Zambia" },
	{ code: "ZW", label: "Zimbabwe" },
] as const;

export type Country = (typeof COUNTRIES)[number];
