CREATE TABLE "store_macro_categories" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "store_macro_categories_name_unique" UNIQUE("name")
);
--> statement-breakpoint
-- Le categorie negozio erano piatte: il livello macro nasce qui, quindi la
-- colonna arriva nullable, si popola e solo dopo diventa NOT NULL. Su un
-- database vuoto le macro restano comunque create e il seed CSV ci si aggancia.
INSERT INTO "store_macro_categories" ("id", "name") VALUES
	(gen_random_uuid()::text, 'Alimentari'),
	(gen_random_uuid()::text, 'Altro'),
	(gen_random_uuid()::text, 'Animali'),
	(gen_random_uuid()::text, 'Auto e moto'),
	(gen_random_uuid()::text, 'Bellezza e benessere'),
	(gen_random_uuid()::text, 'Casa e arredamento'),
	(gen_random_uuid()::text, 'Elettronica e telefonia'),
	(gen_random_uuid()::text, 'Fai da te e giardino'),
	(gen_random_uuid()::text, 'Infanzia e giocattoli'),
	(gen_random_uuid()::text, 'Libri e hobby'),
	(gen_random_uuid()::text, 'Moda e accessori'),
	(gen_random_uuid()::text, 'Ospitalità e viaggi'),
	(gen_random_uuid()::text, 'Ristorazione e locali'),
	(gen_random_uuid()::text, 'Salute'),
	(gen_random_uuid()::text, 'Servizi'),
	(gen_random_uuid()::text, 'Sport e tempo libero')
ON CONFLICT ("name") DO NOTHING;
--> statement-breakpoint
ALTER TABLE "store_categories" ADD COLUMN "macro_category_id" text;--> statement-breakpoint
UPDATE "store_categories" sc
SET "macro_category_id" = m."id"
FROM (VALUES
		('Alimentari', 'Alimentari'),
		('Enoteca', 'Alimentari'),
		('Gastronomia', 'Alimentari'),
		('Macelleria', 'Alimentari'),
		('Negozio bio', 'Alimentari'),
		('Panetteria', 'Alimentari'),
		('Pasticceria', 'Alimentari'),
		('Pescheria', 'Alimentari'),
		('Sex shop (prodotti)', 'Altro'),
		('Acquari', 'Animali'),
		('Dog sitter', 'Animali'),
		('Pet shop', 'Animali'),
		('Toelettatura animali', 'Animali'),
		('Veterinario', 'Animali'),
		('Accessori auto', 'Auto e moto'),
		('Autofficina', 'Auto e moto'),
		('Autolavaggio', 'Auto e moto'),
		('Carrozzeria', 'Auto e moto'),
		('Gommista', 'Auto e moto'),
		('Moto accessori', 'Auto e moto'),
		('Noleggio auto', 'Auto e moto'),
		('Ricambi auto', 'Auto e moto'),
		('Barbiere', 'Bellezza e benessere'),
		('Centro estetico', 'Bellezza e benessere'),
		('Cosmetici', 'Bellezza e benessere'),
		('Make-up professionale', 'Bellezza e benessere'),
		('Massaggi', 'Bellezza e benessere'),
		('Nail salon', 'Bellezza e benessere'),
		('Parrucchiere', 'Bellezza e benessere'),
		('Prodotti capelli', 'Bellezza e benessere'),
		('Profumeria', 'Bellezza e benessere'),
		('Spa', 'Bellezza e benessere'),
		('Trattamenti viso', 'Bellezza e benessere'),
		('Arredamento', 'Casa e arredamento'),
		('Bagno', 'Casa e arredamento'),
		('Casalinghi', 'Casa e arredamento'),
		('Cucine', 'Casa e arredamento'),
		('Decorazioni casa', 'Casa e arredamento'),
		('Elettrodomestici', 'Casa e arredamento'),
		('Illuminazione', 'Casa e arredamento'),
		('Elettronica', 'Elettronica e telefonia'),
		('Gaming', 'Elettronica e telefonia'),
		('Informatica', 'Elettronica e telefonia'),
		('Riparazione PC', 'Elettronica e telefonia'),
		('Riparazione smartphone', 'Elettronica e telefonia'),
		('Sigarette elettroniche', 'Elettronica e telefonia'),
		('Telefonia', 'Elettronica e telefonia'),
		('Bricolage', 'Fai da te e giardino'),
		('Ferramenta', 'Fai da te e giardino'),
		('Fiorista', 'Fai da te e giardino'),
		('Garden center', 'Fai da te e giardino'),
		('Utensili', 'Fai da te e giardino'),
		('Vernici', 'Fai da te e giardino'),
		('Vivai', 'Fai da te e giardino'),
		('Articoli infanzia', 'Infanzia e giocattoli'),
		('Giocattoli', 'Infanzia e giocattoli'),
		('Ludoteca', 'Infanzia e giocattoli'),
		('Cartoleria', 'Libri e hobby'),
		('Fumetteria', 'Libri e hobby'),
		('Hobby creativi', 'Libri e hobby'),
		('Libreria', 'Libri e hobby'),
		('Modellismo', 'Libri e hobby'),
		('Negozio gadget', 'Libri e hobby'),
		('Souvenir', 'Libri e hobby'),
		('Abbigliamento', 'Moda e accessori'),
		('Abbigliamento bambino', 'Moda e accessori'),
		('Abbigliamento donna', 'Moda e accessori'),
		('Abbigliamento uomo', 'Moda e accessori'),
		('Accessori viaggio', 'Moda e accessori'),
		('Borse', 'Moda e accessori'),
		('Gioielleria', 'Moda e accessori'),
		('Intimo', 'Moda e accessori'),
		('Merceria', 'Moda e accessori'),
		('Orologeria', 'Moda e accessori'),
		('Pelletteria', 'Moda e accessori'),
		('Scarpe', 'Moda e accessori'),
		('Second hand', 'Moda e accessori'),
		('Sneakers', 'Moda e accessori'),
		('Valigeria', 'Moda e accessori'),
		('Vintage', 'Moda e accessori'),
		('Affittacamere', 'Ospitalità e viaggi'),
		('Agenzia viaggi', 'Ospitalità e viaggi'),
		('B&B', 'Ospitalità e viaggi'),
		('Hotel', 'Ospitalità e viaggi'),
		('Bar', 'Ristorazione e locali'),
		('Caffetteria', 'Ristorazione e locali'),
		('Gelateria', 'Ristorazione e locali'),
		('Pizzeria', 'Ristorazione e locali'),
		('Pub', 'Ristorazione e locali'),
		('Ristorante', 'Ristorazione e locali'),
		('Centro medico', 'Salute'),
		('Dentista', 'Salute'),
		('Erboristeria', 'Salute'),
		('Fisioterapia', 'Salute'),
		('Parafarmacia', 'Salute'),
		('Agenzia immobiliare', 'Servizi'),
		('Commercialista', 'Servizi'),
		('Copisteria', 'Servizi'),
		('Fotografo', 'Servizi'),
		('Tipografia', 'Servizi'),
		('Articoli sportivi', 'Sport e tempo libero'),
		('Biciclette', 'Sport e tempo libero'),
		('Caccia', 'Sport e tempo libero'),
		('Centro yoga', 'Sport e tempo libero'),
		('Fitness', 'Sport e tempo libero'),
		('Outdoor', 'Sport e tempo libero'),
		('Palestra', 'Sport e tempo libero'),
		('Pesca', 'Sport e tempo libero'),
		('Pilates', 'Sport e tempo libero')
	) AS map(cat, macro)
	JOIN "store_macro_categories" m ON m."name" = map.macro
WHERE sc."name" = map.cat;
--> statement-breakpoint
-- Categorie aggiunte a mano fuori dal CSV: finiscono in "Altro" invece di
-- bloccare la migrazione sul NOT NULL.
UPDATE "store_categories"
SET "macro_category_id" = (SELECT "id" FROM "store_macro_categories" WHERE "name" = 'Altro')
WHERE "macro_category_id" IS NULL;
--> statement-breakpoint
ALTER TABLE "store_categories" ALTER COLUMN "macro_category_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "store_categories" ADD CONSTRAINT "store_categories_macro_category_id_store_macro_categories_id_fk" FOREIGN KEY ("macro_category_id") REFERENCES "public"."store_macro_categories"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "store_categories_macro_id_idx" ON "store_categories" USING btree ("macro_category_id");
